import "server-only";
// Family Board built-in library. Only "question" and "photo" activities exist
// (Drawing was retired). Keys are prefixed q###/p### so older numeric built-ins
// can be retired without touching historical boards. Tuple: [type, text, category, key].
// Categories are internal only (never shown on Today's Board) and exist so a
// family could narrow rotation; the 80/20 question/photo mix is driven by the
// activity cadence, not by these tags. Prompts are interleaved by theme so the
// first cycle (served in key order) never clusters the same topic.
export const boardPrompts = [
  [
    "question",
    "If our family had a mascot, what should it be?",
    "silly",
    "q001",
  ],
  [
    "question",
    "Which one of us would last the longest locked in a grocery store overnight?",
    "imaginative",
    "q002",
  ],
  [
    "question",
    "What food should be banned from our kitchen forever?",
    "family planning",
    "q003",
  ],
  [
    "question",
    "If Max could text, what would he be sending us all day?",
    "silly",
    "q004",
  ],
  [
    "question",
    "Which Disney villain would fit right in at our dinner table?",
    "family planning",
    "q005",
  ],
  [
    "question",
    "Where should we take a trip that we would absolutely not survive?",
    "imaginative",
    "q006",
  ],
  [
    "question",
    "Pancakes or waffles, and who in this family is wrong?",
    "family planning",
    "q007",
  ],
  [
    "question",
    "What is the weirdest thing Dad says all the time?",
    "silly",
    "q008",
  ],
  [
    "question",
    "What is the most useless class they should really teach at school?",
    "imaginative",
    "q009",
  ],
  [
    "question",
    "We have to give Max a terrible new name. What is it?",
    "silly",
    "q010",
  ],
  [
    "question",
    "What is something Mia will probably be famous for one day?",
    "imaginative",
    "q011",
  ],
  [
    "question",
    "Best movie we have all actually watched together?",
    "family planning",
    "q012",
  ],
  [
    "question",
    "What is a tiny thing someone here does that you love?",
    "reflective",
    "q013",
  ],
  [
    "question",
    "Who in the family is the worst loser at a game?",
    "silly",
    "q014",
  ],
  [
    "question",
    "What is one house rule every family should secretly have?",
    "imaginative",
    "q015",
  ],
  [
    "question",
    "If we opened a restaurant, what would we flat-out refuse to serve?",
    "family planning",
    "q016",
  ],
  [
    "question",
    "Max gets to talk for five minutes. What is your first question for him?",
    "silly",
    "q017",
  ],
  [
    "question",
    "In a house fire, what pointless thing would each of us grab?",
    "imaginative",
    "q018",
  ],
  [
    "question",
    "Which one of us is basically a Disney sidekick?",
    "family planning",
    "q019",
  ],
  [
    "question",
    "What is the worst possible theme for a family vacation?",
    "imaginative",
    "q020",
  ],
  [
    "question",
    "What sound does someone in this house make that drives you up the wall?",
    "silly",
    "q021",
  ],
  [
    "question",
    "Would you rather have Max's life or Dad's for a week?",
    "imaginative",
    "q022",
  ],
  ["question", "Funniest possible name for our house?", "silly", "q023"],
  [
    "question",
    "What food could you happily eat every single day forever?",
    "family planning",
    "q024",
  ],
  ["question", "Who would win a staring contest against Max?", "silly", "q025"],
  [
    "question",
    "If Mia were principal for a day, what is her first rule?",
    "imaginative",
    "q026",
  ],
  [
    "question",
    "What will our family still be arguing about ten years from now?",
    "imaginative",
    "q027",
  ],
  [
    "question",
    "Most overrated snack in this house?",
    "family planning",
    "q028",
  ],
  [
    "question",
    "If we all swapped rooms tonight, who complains first?",
    "silly",
    "q029",
  ],
  [
    "question",
    "If our family were a movie, what genre would it be?",
    "imaginative",
    "q030",
  ],
  [
    "question",
    "What city could our family never handle living in?",
    "family planning",
    "q031",
  ],
  [
    "question",
    "Where does Max think we go when we leave the house?",
    "silly",
    "q032",
  ],
  ["question", "What is a phrase Mom says way too often?", "silly", "q033"],
  [
    "question",
    "Beach trip or theme park, and defend your answer.",
    "family planning",
    "q034",
  ],
  [
    "question",
    "We are inventing a family holiday. What are we celebrating?",
    "imaginative",
    "q035",
  ],
  ["question", "Who is most likely to cry at a cartoon?", "silly", "q036"],
  [
    "question",
    "Best thing we have ever eaten on a trip?",
    "family planning",
    "q037",
  ],
  ["question", "If Max had a rapper name, what would it be?", "silly", "q038"],
  [
    "question",
    "Stranded on an island together, whose job is finding the food?",
    "imaginative",
    "q039",
  ],
  [
    "question",
    "What is a family memory that still makes you laugh?",
    "reflective",
    "q040",
  ],
  ["question", "Which Disney ride is the most us?", "family planning", "q041"],
  [
    "question",
    "What is the most ridiculous excuse to get out of school or work?",
    "silly",
    "q042",
  ],
  [
    "question",
    "Name a pizza topping that should honestly be illegal.",
    "family planning",
    "q043",
  ],
  [
    "question",
    "What trend will Mia look back on and cringe about?",
    "imaginative",
    "q044",
  ],
  [
    "question",
    "Who is best at pretending they are not asleep on the couch?",
    "silly",
    "q045",
  ],
  [
    "question",
    "What does our family do that other people would find strange?",
    "family planning",
    "q046",
  ],
  [
    "question",
    "Would you rather never eat dessert again or never watch TV again?",
    "imaginative",
    "q047",
  ],
  [
    "question",
    "We can teleport to dinner anywhere tonight. Where are we going?",
    "family planning",
    "q048",
  ],
  [
    "question",
    "What belongs in our family's secret handshake?",
    "silly",
    "q049",
  ],
  [
    "question",
    "If Max ran the house for a day, what changes immediately?",
    "silly",
    "q050",
  ],
  [
    "question",
    "Which one of us would survive the longest in a haunted house?",
    "imaginative",
    "q051",
  ],
  [
    "question",
    "Favorite thing we do together on a lazy weekend?",
    "family planning",
    "q052",
  ],
  ["question", "Give our next pet the worst name imaginable.", "silly", "q053"],
  [
    "question",
    "Which Disney character would be exhausting to actually live with?",
    "family planning",
    "q054",
  ],
  [
    "question",
    "What subject should school replace with something genuinely useful?",
    "imaginative",
    "q055",
  ],
  [
    "question",
    "What meal do we make way too often?",
    "family planning",
    "q056",
  ],
  [
    "question",
    "Who is most likely to get lost in their own neighborhood?",
    "silly",
    "q057",
  ],
  [
    "question",
    "What is one thing we will still be doing together in twenty years?",
    "reflective",
    "q058",
  ],
  [
    "question",
    "What is the most Dad thing Dad has ever done?",
    "silly",
    "q059",
  ],
  [
    "question",
    "Morning people or night owls, and who is actually winning?",
    "imaginative",
    "q060",
  ],
  [
    "question",
    "What is a place we have been that you would go back to tomorrow?",
    "family planning",
    "q061",
  ],
  [
    "question",
    "If we started a family YouTube channel, what would it be about?",
    "imaginative",
    "q062",
  ],
  [
    "question",
    "What is Max's most dramatic personality trait?",
    "silly",
    "q063",
  ],
  [
    "question",
    "The power is out for a week. Who cracks first?",
    "imaginative",
    "q064",
  ],
  ["question", "Best gift someone here has ever given?", "reflective", "q065"],
  [
    "question",
    "If we did a matching family costume, what should it be?",
    "family planning",
    "q066",
  ],
  [
    "question",
    "Who gives the worst advice, and who gives the best?",
    "silly",
    "q067",
  ],
  [
    "question",
    "What food combo do you love that grosses everyone else out?",
    "family planning",
    "q068",
  ],
  [
    "question",
    "What is the hardest job in this house that nobody appreciates?",
    "imaginative",
    "q069",
  ],
  ["question", "Best fake name to give at a coffee shop?", "silly", "q070"],
  [
    "question",
    "What job would Mia be secretly great at someday?",
    "imaginative",
    "q071",
  ],
  [
    "question",
    "What is a habit someone here has that is oddly charming?",
    "reflective",
    "q072",
  ],
  ["question", "Worst part of any road trip?", "family planning", "q073"],
  [
    "question",
    "Would you rather be stuck in an elevator with Max or a total stranger?",
    "imaginative",
    "q074",
  ],
  [
    "question",
    "Who would be the first voted off our family island?",
    "silly",
    "q075",
  ],
  [
    "question",
    "You get one chore done for you forever. Which do you pick?",
    "imaginative",
    "q076",
  ],
  [
    "question",
    "What movie could you watch a hundred times and never get sick of?",
    "family planning",
    "q077",
  ],
  [
    "question",
    "The single most disappointing dessert, name it.",
    "family planning",
    "q078",
  ],
  [
    "question",
    "Invent a punishment for whoever leaves dishes in the sink.",
    "silly",
    "q079",
  ],
  [
    "question",
    "If Max wrote a review of our house, what would it say?",
    "silly",
    "q080",
  ],
  [
    "question",
    "What is your favorite thing about where we live?",
    "family planning",
    "q081",
  ],
  [
    "question",
    "We all have to share one phone. Who ruins it first?",
    "silly",
    "q082",
  ],
  [
    "question",
    "What is something you learned this week that surprised you?",
    "reflective",
    "q083",
  ],
  [
    "question",
    "Name a band we could start with only the people in this house.",
    "silly",
    "q084",
  ],
  [
    "question",
    "What souvenir do we always buy and never actually use?",
    "family planning",
    "q085",
  ],
  ["question", "Who is most likely to start a food fight?", "silly", "q086"],
  [
    "question",
    "Cats or dogs, and does Max get a vote?",
    "family planning",
    "q087",
  ],
  [
    "question",
    "Which of us would be the worst contestant on a game show?",
    "imaginative",
    "q088",
  ],
  [
    "question",
    "What is a fancy food that is honestly just not that good?",
    "family planning",
    "q089",
  ],
  [
    "question",
    "Name a word our family uses that we probably made up.",
    "silly",
    "q090",
  ],
  [
    "question",
    "What is something we will laugh about years from now?",
    "reflective",
    "q091",
  ],
  [
    "question",
    "If our family had a theme song, what would it be?",
    "imaginative",
    "q092",
  ],
  [
    "question",
    "What does Max do that makes absolutely no sense?",
    "silly",
    "q093",
  ],
  [
    "question",
    "We can add one room to the house. What is in it?",
    "imaginative",
    "q094",
  ],
  [
    "question",
    "What is the best day we have had together recently?",
    "reflective",
    "q095",
  ],
  [
    "question",
    "Who is the most dramatic when they are a little bit sick?",
    "silly",
    "q096",
  ],
  [
    "question",
    "Where would you take someone visiting our town first?",
    "family planning",
    "q097",
  ],
  [
    "question",
    "Swap jobs with Mom or Dad for a day. Which, and why?",
    "imaginative",
    "q098",
  ],
  [
    "question",
    "What is the one snack everybody here agrees on?",
    "family planning",
    "q099",
  ],
  [
    "question",
    "Would you rather always be ten minutes early or ten minutes late?",
    "imaginative",
    "q100",
  ],
  [
    "question",
    "What would be a terrible name for a baby but a great name for a goldfish?",
    "silly",
    "q101",
  ],
  [
    "question",
    "Which Disney movie has the best songs, no debate?",
    "family planning",
    "q102",
  ],
  [
    "question",
    "Who is most likely to talk to Max like he understands every word?",
    "silly",
    "q103",
  ],
  [
    "question",
    "We found a treasure map. Who leads the expedition?",
    "imaginative",
    "q104",
  ],
  [
    "question",
    "What is a thing Dad does that we all secretly copy?",
    "reflective",
    "q105",
  ],
  ["question", "Best thing to eat at midnight?", "family planning", "q106"],
  [
    "question",
    "What is a skill you want the whole family to learn together?",
    "family planning",
    "q107",
  ],
  [
    "question",
    "How long could we survive in one tiny cabin together?",
    "imaginative",
    "q108",
  ],
  [
    "question",
    "What is a small thing that reliably makes your day better?",
    "reflective",
    "q109",
  ],
  ["question", "Who is the loudest chewer in this family?", "silly", "q110"],
  [
    "question",
    "Make one house rule that only applies to Dad.",
    "silly",
    "q111",
  ],
  [
    "question",
    "If Max had a job, what would he be terrible at?",
    "silly",
    "q112",
  ],
  [
    "question",
    "Would you rather have unlimited pizza or unlimited ice cream?",
    "family planning",
    "q113",
  ],
  [
    "question",
    "If we all got superpowers, whose would be the most dangerous?",
    "imaginative",
    "q114",
  ],
  [
    "question",
    "What show could our whole family binge without arguing?",
    "family planning",
    "q115",
  ],
  ["question", "Most pointless thing you had to do today?", "silly", "q116"],
  [
    "question",
    "Best name for a boat we will definitely never own?",
    "silly",
    "q117",
  ],
  [
    "question",
    "What food do we fight over the leftovers of?",
    "family planning",
    "q118",
  ],
  [
    "question",
    "What do you think Mia will be obsessed with next?",
    "imaginative",
    "q119",
  ],
  [
    "question",
    "What is something you hope we never stop doing as a family?",
    "reflective",
    "q120",
  ],
  ["question", "Who gives the best hugs?", "reflective", "q121"],
  [
    "question",
    "What is a trip we keep talking about but never take?",
    "family planning",
    "q122",
  ],
  [
    "question",
    "What is the most our-family thing that happened this week?",
    "family planning",
    "q123",
  ],
  [
    "question",
    "We hired a butler. What is the first thing you make him do?",
    "silly",
    "q124",
  ],
  ["question", "What would Max's dream day look like?", "silly", "q125"],
  [
    "question",
    "Would you rather live at Disney World or on a cruise ship?",
    "imaginative",
    "q126",
  ],
  [
    "question",
    "Which character would you want narrating your life?",
    "imaginative",
    "q127",
  ],
  ["question", "Best meal Mom or Dad makes?", "family planning", "q128"],
  [
    "question",
    "What should our family's official motto be?",
    "imaginative",
    "q129",
  ],
  [
    "question",
    "Who is most likely to win an award for most extra?",
    "silly",
    "q130",
  ],
  [
    "question",
    "What is a food you hated as a kid but love now?",
    "family planning",
    "q131",
  ],
  [
    "question",
    "We each pick one movie to live inside. Which is yours?",
    "imaginative",
    "q132",
  ],
  [
    "question",
    "What is the best thing that happened at school or work today?",
    "family planning",
    "q133",
  ],
  [
    "question",
    "Name a cereal that should exist but does not.",
    "silly",
    "q134",
  ],
  [
    "question",
    "What is the strangest thing we have ever seen on a trip?",
    "family planning",
    "q135",
  ],
  [
    "question",
    "If Max could eat one human food forever, what is it?",
    "silly",
    "q136",
  ],
  ["question", "Your prediction for this weekend?", "imaginative", "q137"],
  [
    "question",
    "What does someone here always say right before trouble starts?",
    "silly",
    "q138",
  ],
  [
    "question",
    "Who would be the best at hosting a game show?",
    "imaginative",
    "q139",
  ],
  [
    "question",
    "Your comfort movie when you are home sick?",
    "family planning",
    "q140",
  ],
  [
    "question",
    "Would you rather give up your phone or dessert for a month?",
    "imaginative",
    "q141",
  ],
  [
    "question",
    "What is a snack that somehow tastes better at someone else's house?",
    "family planning",
    "q142",
  ],
  [
    "question",
    "We can freeze time for one hour. What do we do?",
    "imaginative",
    "q143",
  ],
  [
    "question",
    "Which of us would cry the most at a Disney movie?",
    "family planning",
    "q144",
  ],
  [
    "question",
    "Invent a holiday this family would genuinely celebrate.",
    "imaginative",
    "q145",
  ],
  ["question", "Most spoiled thing about Max's life?", "silly", "q146"],
  [
    "question",
    "Who is the messiest, and who only pretends they are not?",
    "silly",
    "q147",
  ],
  ["question", "Best snack for a long car ride?", "family planning", "q148"],
  [
    "question",
    "What is one thing you want to try before the year ends?",
    "family planning",
    "q149",
  ],
  [
    "question",
    "What is a moment from this year you would want to keep?",
    "reflective",
    "q150",
  ],
  [
    "question",
    "What phrase instantly means we are running late?",
    "silly",
    "q151",
  ],
  [
    "question",
    "We each get amazing at one sport overnight. What do you pick?",
    "imaginative",
    "q152",
  ],
  [
    "question",
    "The perfect family pizza order, settle it.",
    "family planning",
    "q153",
  ],
  [
    "question",
    "Who is most likely to fall asleep first at a movie?",
    "silly",
    "q154",
  ],
  [
    "question",
    "Which of us gets kicked out of a Disney park first?",
    "imaginative",
    "q155",
  ],
  [
    "question",
    "Would you rather sing everything you say or dance everywhere you go?",
    "imaginative",
    "q156",
  ],
  [
    "question",
    "If Max wrote us a to-do list, what would be on it?",
    "silly",
    "q157",
  ],
  [
    "question",
    "Best part of coming home after being away?",
    "reflective",
    "q158",
  ],
  [
    "question",
    "What is a job you would be weirdly good at?",
    "imaginative",
    "q159",
  ],
  [
    "question",
    "Best name for a superhero whose only power is naps?",
    "silly",
    "q160",
  ],
  [
    "question",
    "Where should we go the next free weekend we all have?",
    "family planning",
    "q161",
  ],
  [
    "question",
    "Our family enters a talent show. What is our act?",
    "imaginative",
    "q162",
  ],
  [
    "question",
    "What dinner should we add to the regular rotation?",
    "family planning",
    "q163",
  ],
  ["question", "Who is best at making everyone laugh?", "reflective", "q164"],
  ["question", "Weirdest thing in our fridge right now?", "silly", "q165"],
  [
    "question",
    "What is something Mia will teach us before we teach her?",
    "reflective",
    "q166",
  ],
  [
    "question",
    "What movie quote does our family use way too much?",
    "family planning",
    "q167",
  ],
  [
    "question",
    "Would you rather have a pool or a trampoline?",
    "imaginative",
    "q168",
  ],
  ["question", "What would Max's superhero name be?", "silly", "q169"],
  [
    "question",
    "If we had a family flag, what is on it?",
    "imaginative",
    "q170",
  ],
  [
    "question",
    "We all camp in the backyard tonight. Who has the most fun?",
    "imaginative",
    "q171",
  ],
  [
    "question",
    "Where in the house do you feel the most relaxed?",
    "reflective",
    "q172",
  ],
  [
    "question",
    "What is the most extra thing we have ever made for a holiday meal?",
    "family planning",
    "q173",
  ],
  [
    "question",
    "Who takes the longest to get ready, honestly?",
    "silly",
    "q174",
  ],
  [
    "question",
    "What is a country you would love for us all to visit someday?",
    "family planning",
    "q175",
  ],
  [
    "question",
    "What chore would you happily do to get out of a different one?",
    "silly",
    "q176",
  ],
  [
    "question",
    "Name an ice cream flavor that should never be invented.",
    "silly",
    "q177",
  ],
  [
    "question",
    "If our life had a laugh track, what moment would it replay most?",
    "imaginative",
    "q178",
  ],
  [
    "question",
    "What do you think will be totally different by next year?",
    "imaginative",
    "q179",
  ],
  [
    "question",
    "What is something you are glad the four of us get to do together?",
    "reflective",
    "q180",
  ],
  [
    "question",
    "What tiny habit instantly says this is Dad?",
    "reflective",
    "q181",
  ],
  [
    "question",
    "Who is most likely to become internet famous by accident?",
    "silly",
    "q182",
  ],
  [
    "question",
    "We each un-invent one thing. What is going?",
    "imaginative",
    "q183",
  ],
  ["question", "Best thing to bake on a cold day?", "family planning", "q184"],
  [
    "question",
    "Would you rather have breakfast for every meal or dessert for every meal?",
    "family planning",
    "q185",
  ],
  [
    "question",
    "What is Max's most annoying habit and his most lovable one?",
    "silly",
    "q186",
  ],
  ["question", "Best part of staying in a hotel?", "family planning", "q187"],
  [
    "question",
    "Which of us is most likely to randomly burst into song?",
    "family planning",
    "q188",
  ],
  [
    "question",
    "Who is the calmest when everything goes wrong?",
    "reflective",
    "q189",
  ],
  [
    "question",
    "If we made one family tradition mandatory forever, what is it?",
    "reflective",
    "q190",
  ],
  [
    "question",
    "What is a goal we could work on together this month?",
    "family planning",
    "q191",
  ],
  [
    "question",
    "You plus one other person here form a detective duo. Team name?",
    "silly",
    "q192",
  ],
  [
    "question",
    "What is the perfect movie-night snack lineup?",
    "family planning",
    "q193",
  ],
  [
    "question",
    "One trip in a time machine: past or future?",
    "imaginative",
    "q194",
  ],
  [
    "question",
    "What do we always say we will do next time and never do?",
    "family planning",
    "q195",
  ],
  [
    "question",
    "What is your favorite thing about weekends with us?",
    "reflective",
    "q196",
  ],
  [
    "question",
    "Who is most likely to try to adopt ten more dogs?",
    "silly",
    "q197",
  ],
  [
    "question",
    "What small adventure could we have this week without going far?",
    "family planning",
    "q198",
  ],
  [
    "question",
    "If our family got a reality show, what would they title it?",
    "imaginative",
    "q199",
  ],
  [
    "question",
    "What is a little moment from today worth remembering?",
    "reflective",
    "q200",
  ],
  [
    "photo",
    "Take a picture of the weirdest thing you can see right now.",
    "silly",
    "p001",
  ],
  [
    "photo",
    "Show us something that made you smile today.",
    "family planning",
    "p002",
  ],
  [
    "photo",
    "Snap your current view, exactly as it is.",
    "family planning",
    "p003",
  ],
  ["photo", "Find something near you that looks like a face.", "silly", "p004"],
  [
    "photo",
    "Take a picture of something in your favorite color.",
    "imaginative",
    "p005",
  ],
  ["photo", "Show us the most ridiculous thing within reach.", "silly", "p006"],
  [
    "photo",
    "Photograph something you wish you could take home.",
    "family planning",
    "p007",
  ],
  [
    "photo",
    "Take a picture of your snack, or the crumbs of it.",
    "family planning",
    "p008",
  ],
  [
    "photo",
    "Find something that reminds you of one of us.",
    "reflective",
    "p009",
  ],
  ["photo", "Show us something unexpectedly pretty.", "reflective", "p010"],
  ["photo", "Take the worst selfie you possibly can.", "silly", "p011"],
  [
    "photo",
    "Find something that would make a truly terrible gift.",
    "silly",
    "p012",
  ],
  ["photo", "Show us the coziest spot near you.", "reflective", "p013"],
  [
    "photo",
    "Photograph something Max would try to eat in one second.",
    "silly",
    "p014",
  ],
  ["photo", "Take a picture of the sky right now.", "family planning", "p015"],
  ["photo", "Find something that is older than Mia.", "imaginative", "p016"],
  ["photo", "Show us a color you are wearing today.", "imaginative", "p017"],
  [
    "photo",
    "Take a picture of something that badly needs cleaning.",
    "silly",
    "p018",
  ],
  ["photo", "Find the comfiest-looking spot around you.", "reflective", "p019"],
  [
    "photo",
    "Show us something that smells really good.",
    "family planning",
    "p020",
  ],
  [
    "photo",
    "Take a picture of the most-used thing near you.",
    "imaginative",
    "p021",
  ],
  [
    "photo",
    "Find something that looks more expensive than it is.",
    "silly",
    "p022",
  ],
  ["photo", "Show us what is on your feet right now.", "silly", "p023"],
  [
    "photo",
    "Take a picture of something you would grab if we moved tomorrow.",
    "reflective",
    "p024",
  ],
  ["photo", "Find the brightest thing you can see.", "imaginative", "p025"],
  [
    "photo",
    "Show us your favorite mug, cup, or water bottle.",
    "family planning",
    "p026",
  ],
  [
    "photo",
    "Take a picture of something perfectly round.",
    "imaginative",
    "p027",
  ],
  [
    "photo",
    "Find something that would make everyone here laugh.",
    "silly",
    "p028",
  ],
  [
    "photo",
    "Show us the view out the nearest window.",
    "family planning",
    "p029",
  ],
  ["photo", "Take a picture of something soft.", "imaginative", "p030"],
  [
    "photo",
    "Find the messiest corner around you and just own it.",
    "silly",
    "p031",
  ],
  [
    "photo",
    "Show us something that tastes better than it looks.",
    "family planning",
    "p032",
  ],
  [
    "photo",
    "Take a picture of your bag, backpack, or pockets today.",
    "family planning",
    "p033",
  ],
  ["photo", "Find something that has seen better days.", "silly", "p034"],
  [
    "photo",
    "Show us a snack you would share with Max but really should not.",
    "silly",
    "p035",
  ],
  [
    "photo",
    "Take a picture of the best light in the room right now.",
    "reflective",
    "p036",
  ],
  ["photo", "Find something with a funny label or sign.", "silly", "p037"],
  [
    "photo",
    "Show us your setup right now, desk or couch or wherever you are.",
    "family planning",
    "p038",
  ],
  [
    "photo",
    "Take a picture of something you use every single day.",
    "imaginative",
    "p039",
  ],
  [
    "photo",
    "Find something that could survive being knocked over by Max.",
    "silly",
    "p040",
  ],
  [
    "photo",
    "Show us the prettiest thing you can find outside.",
    "reflective",
    "p041",
  ],
  [
    "photo",
    "Take a picture of a snack you would never share.",
    "family planning",
    "p042",
  ],
  [
    "photo",
    "Find something that looks like it belongs in a museum, but does not.",
    "silly",
    "p043",
  ],
  [
    "photo",
    "Show us what home looks like from where you are sitting.",
    "reflective",
    "p044",
  ],
  [
    "photo",
    "Take a picture of the weather right now.",
    "family planning",
    "p045",
  ],
  [
    "photo",
    "Find the smallest interesting thing near you.",
    "imaginative",
    "p046",
  ],
  [
    "photo",
    "Show us something that would make a great phone wallpaper.",
    "imaginative",
    "p047",
  ],
  [
    "photo",
    "Take a picture of something that is clearly Mia's, Mom's, Dad's, or Max's.",
    "family planning",
    "p048",
  ],
  [
    "photo",
    "Find something that always ends up lost in this house.",
    "silly",
    "p049",
  ],
  [
    "photo",
    "Show us one thing that made today a good day.",
    "reflective",
    "p050",
  ],
] as const;
